### PR TITLE
Add note about stand-alone usage

### PR DESCRIPTION
**Pull request by simurai**
Closes https://github.com/atom/atom-ui/issues/6

### CODE REVIEW

**Comment by darmie** [comment]
Hi @simurai I would like to know the status of the standalone version of atom-ui. I have an electron project and I don't want to clone the Atom editor. Thanks

**Comment by simurai** [comment]
There isn't any plan for a standalone version of atom-ui at the moment.

Something you could try tough:
1. Find an Atom theme you like, then import its `ui-variables.less` file.
2. Import `atom-ui.less`.

``` less
@import "../node_modules/atom-theme/styles/ui-variables.less";
@import "../node_modules/atom-ui/atom-ui.less";
```

Then the variables that atom-ui uses should be available.

**Comment by simurai** [comment]
If ☝️  doesn't work, maybe using an existing UI library might be ok too. Like [Photon](http://photonkit.com/), Bootsrap, Foundation etc.

**Comment by darmie** [comment]
Thanks

**Comment by darmie** [comment]
@simurai successfully compiled by including .less files from atom's core static assets.

**Pull request merged**
